CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha_hash TEXT NOT NULL,
  curso TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
